cc_test(
    name = "span-context",
    srcs = [
        "span-context_unittest.cc",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "span",
    srcs = [
        "span_unittest.cc",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "tracer",
    srcs = [
        "tracer_unittest.cc",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "tracer-registry",
    srcs = [
        "tracer-registry_unittest.cc",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)
